FROM graylog/graylog:3.1
#RUN wget -O /usr/share/graylog/plugin/graylog-plugin-auth-sso-3.0.0.jar https://github.com/Graylog2/graylog-plugin-auth-sso/releases/download/3.0.0/graylog-plugin-auth-sso-3.0.0.jar
#ADD /home/bbelliv/Documents/docs/desktop/terra/auto-ops/greylog-docker/graylog/config /home/bbelliv/Documents/docs/desktop/terra/auto-ops/greylog-docker/graylog/config/graylog-plugin-auth-sso-3.0.0.jar 
#ADD /home/bbelliv/Documents/docs/desktop/terra/auto-ops/greylog-docker/graylog/config/ /home/bbelliv/Documents/docs/desktop/terra/auto-ops/greylog-docker/graylog/config/graylog-plugin-auth-sso-3.0.0.jar
#ADD ./director_80.conf /etc/nginx/conf.d/